### ISSUE TITLE
Add structs for clevis pins

### ISSUE THREAD

**Issue by lack** [anatol/clevis.go#4] opened 2021-06-05 11:39 UTC
Rather than just using raw `map[string] interface{}` when dealing with these clevis pin configurations, it would be convenient to provide a struct with full json marshalling/unmarshalling.

**Comment by anatol** [comment] 2021-06-05 15:49
Pin configuration does not use `map[string] interface{}`. Pin data headers do. But parsing headers happens inside `jwx` library. It returned to us in parsed form by `msg.ProtectedHeaders().Get("clevis")` as `map[string] interface{}`. I am not sure what we can do here.

**Comment by lack** [comment] 2021-06-18 02:46
We could take that map[string] interface{} and parse that into a struct, couldn't we?

**Comment by anatol** [comment] 2021-06-18 03:44
Could you please give an example of such code in go?

**Comment by lack** [comment] 2021-06-21 20:51
I'll try when I get a moment :)

**Comment by lack** [comment] 2021-06-21 21:02
One option I've crowd-sourced is something like this: https://play.golang.org/p/MYwJ65p-T3xa, another is https://github.com/mitchellh/mapstructure

**Comment by lack** [comment] 2021-06-21 21:33
It also looks like this https://github.com/lestrrat-go/jwx/blob/b2a462edc2c28967867df7da4e759f69ae1a9e4b/internal/json/registry.go Registry may let us register a specific gnostic object for a specific key name so the "clevis" part gets unmarshalled into a struct we supply, maybe?

**Comment by lack** [comment] 2021-06-21 21:36
Yes - Maybe here!  https://github.com/lestrrat-go/jwx/blob/b2a462edc2c28967867df7da4e759f69ae1a9e4b/jwe/jwe.go#L308

If we just call 'jwe.RegisterCustomField("clevis", ClevisPin)', it looks like it will decode things for us automatically!  I'm going to try to prove this out.

**Comment by lack** [comment] 2021-06-25 04:56
I just hit a really cool edge-case when testing my struct-based sss decryption.  By chance I happened to write my SssPin struct in a different order than what the original latchset/clevis code happens to provide.  The `jwe.RegisterCustomField` mechanism was happy to fully parse the json into my struct in whatever order, and I was able to decrypt each of the pins into their associated points just fine; but when it came time to decrypt the message things fell apart:

1. The 'clevis' header is a protected header, so any alteration to this header will fail message authentication
2. Using `jwe.RegisterCustomField()` parses the real data into the real struct, but when it comes time to marshal this struct back into the byte stream that is to be authenticated, it doesn't maintain a copy of the original data, but actually marshals the real struct.
3. This real struct ended up with identical data but in a different order in the 'clevis' protected header
4. Message authentication failed!

I think the real fix for this is probably in the jwe library, and I may log an issue there: It should not use deserialized-serialized versions of protected headers when doing `msg.Decrypt(...)` but instead maintain its own protected copy of protected headers - But it turns out we can be tolerant of this by only registering that our header be available as a `json.RawMessage` and then doing a secondary unmarshalling of this data to our own Pin structure.

**Comment by anatol** [comment] 2021-06-25 16:45
> but when it comes time to marshal this struct back into the byte stream that is to be authenticated, it doesn't maintain a copy of the original data, but actually marshals the real struct.

I need a bit more context here. When and who marshals it back? Could you give a simple test case for this issue?

> This real struct ended up with identical data but in a different order in the 'clevis' protected header
> Message authentication failed!

How does the authentication tag calculated? Is it calculated for the header properties value **before** it is marshalled?

cc @lestrrat for comments.

**Comment by lestrrat** [comment] 2021-06-25 21:00
I'm completely lacking the why and what for of this issue, but here are my takes from what I could reduce by a quick glance on this subject:

Right,  don't deserialize and serialize again for verification. 
This method not only breaks for key orders changing, but the moment you start reading the JWx RFCs, you realize that the RFC is using a protected headers that are serialized as:

```
{"foo": "bar",
 "baz": "quux"}`
```

Which is like the most insane JSON serialization, with newlines and indentations at the most unexpected places, ....but nonetheless, this is valid, and this is when you realize that you can't know _how_ the original data was serialized to begin with, let alone some library messing up the field order.

Yes, I did briefly pondered about keeping a copy of the raw []byte for each sensitive field(s) within my library's structs, so that I can use those for re-computation later, but I believe this approach is not only error prone, but moreover, what happens when somebody makes a change to the struct data. For example, what if the user wanted to change the deserialized protected headers - what should the library do at that point? Specifically, what happens to verification tools that want to verify this data ... do we see look at the original []byte, or do we recalculate because the struct has changed. It's messy.

And on top of that, there are users don't ever do the recomputation afterwards. For these people keeping around the original data is a total waste of memory.

---

My personal take on this -- and as always, I'm willing to be convinced otherwise given solid code/evidence -- is for end users to keep a copy of the original encrypted/signed data, and only use that for verification purposes, and don't ever expect to be able to reuse deserialized data for verification purposes

**Comment by lack** [comment] 2021-06-26 00:34
I will try to come up with a tidy code example in the next week or two, but I think I can give a quick summary of how I see the lwe library bug.  In short, doing a Get of a protected header can have unexpected and inconsistent side-effects:
- If I don't ever call `jwe.RegisterCustomField("foo", Foo{})`, I can do a `msg.ProtectedHeaders().Get("foo")` followed by `msg.Decrypt(...)` and it will succeed.
- If I call `jwe.RegisterCustomField("foo", json.RawMessage{})`, again I can do the protected header `Get("foo")` followed by `msg.Decrypt(...)` and it will succeed.
- If I do call `jwe.RegisterCustomField("foo", Foo{})`, here's where the inconsistencies pop up:
- a. If Foo{} happens to match the field order in the original jwe message, doing a Get then Decrypt succeeds.
- b. If Foo{} has the fields in a different order, or someone forgets an "omitempty" tag, the Get succeeds but the Decrypt unexpectedly fails. Even if I never alter any of the fields of the struct that's parsed for me.

Part of this may be my naive expectation that doing a Get of a header is a read-only operation, but maybe that's a possible answer to your later question: If I do a Get but no Set, I would assume I want the data to remain unaltered, regardless of how it's returned to me. As soon as I do a Set, I should expect to have invalidated a protected header's hash/signature/protection.

**Comment by lestrrat** [comment] 2021-06-26 00:47
Sounds like one-thirds each of (1) lack of documentation/bad API, (2) unexpected usage, and a (3) bug  

For 1 and 2, I don't immediately remember the details, but I think `(jwe.Message).Decrypt` was ever written to be a robust tool to be used by the end user. And `jwe.RegisterCustomField` does modify the structure of a `jwe.Message`, which again is inherently not great to verify encryption/signature.

For 3, I don't know. What you describe does sound a bit fishy, which should probably be fixed. But again, I don't think you should really be using `msg.Decrypt`. If what you are saying is that `jwe.Decrypt` eventually calls `msg.Decrypt` which is when the problem occurs, yeah, that's a bug :)

**Comment by anatol** [comment] 2021-06-26 01:14
`msg.Decrypt` is a part of public API and it is expected that some users start depending on it.

>  I don't think you should really be using msg.Decrypt. If what you are saying is that jwe.Decrypt eventually calls msg.Decrypt

Could you please provide more rationale behind this statement? `jwe.Decrypt` looks like a thin wrapper over `msg.Decrypt`. `jwe.Decrypt` parses the message and calls `msg.Decrypt`. But I already have the parsed message, parsing it again seems like an unneeded operation.

**Comment by lestrrat** [comment] 2021-06-26 02:20
Right, that's why I said it is a part doc problem. IIRC, the reason it exists is because it is sometimes desirable to craft a JWE message by hand.

At the same time, I think jwe.Message should either be readonly (parse the message, but never serialize again) or writeonly (create/update as you wish and serialize, but only from scratch).

The reasoning is orecisely because of the asymmetry in the serialization and deserialization.

**Comment by lack** [comment] 2021-06-26 04:39
> >  I don't think you should really be using msg.Decrypt. If what you are saying is that jwe.Decrypt eventually calls msg.Decrypt
> 
> Could you please provide more rationale behind this statement? `jwe.Decrypt` looks like a thin wrapper over `msg.Decrypt`. `jwe.Decrypt` parses the message and calls `msg.Decrypt`. But I already have the parsed message, parsing it again seems like an unneeded operation.

This suggestion (calling `jwe.Decrypt` and passing in the fresh unaltered byte array directly) was what I tried first when I hit the message authentication problem.  But I can demonstrate that `jwe.Decrypt()` calls the exact same `jwe.Parse(buf)` which introduces the same side-effect if you've registered a custom field parser for a protected header.

**Comment by lestrrat** [comment] 2021-06-26 05:57
@lack Okay, that is most likely a bug! Please give me a reproducible testcase

**Comment by anatol** [comment] 2021-06-26 17:08
Extracted a testcase for this custom field bug and filed it separately. Let's track it there.

**Comment by lack** [comment] 2021-06-27 00:09
@anatol Thanks for doing that for me!

**Comment by anatol** [comment] 2021-06-27 00:34
> @anatol Thanks for doing that for me!

Sure thing. Could you please send your 'pin' change as a PR? Let's review it while the jwx issue is tracked in parallel.

**Comment by anatol** [comment] 2021-07-06 17:43
@lack do you plan to work on using the latest `jwe` changes? If not I can pick it up and finish that work.

**Comment by anatol** [comment] 2021-07-06 17:45
The Pin change from @lack got merged as https://github.com/anatol/clevis.go/commit/5fc68e162a35d9a577c8d0b2d6511252d8d7e26c

**Closed by anatol** 2021-07-06 17:45 UTC

**Comment by lack** [comment] 2021-07-06 17:56
> @lack do you plan to work on using the latest `jwe` changes? If not I can pick it up and finish that work.

I was going to give it a shot, but some personal issues popped up this week that interrupted my plans.  Let me know if you're working on it, and I won't start :)

**Comment by lack** [comment] 2021-07-07 02:43
@anatol I saw your commit for the jwx change, but I was going to approach it slightly differently: https://github.com/lack/clevis.go/commit/c71a4b0d8b5a4bcb5c93c93fa3a75ad86b75d635
